global:
  scrape_interval: "1m"

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 1m
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "Node-Exporter"
    scrape_interval: 1m
    static_configs:
      - targets: ["node-exporter:9100"]

  - job_name: "Azure-Cloud-Exporter"
    scrape_interval: 1m
    static_configs:
      - targets: ["192.168.0.111:5000"]

  - job_name: "Azure-DevOps-Exporter"
    scrape_interval: 1m
    static_configs:
      - targets: ["192.168.0.110:6000"]