{
 "title": "Azure DevOps example",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DataSource", "query": "prometheus" },
   {
    "name": "Project",
    "query": {
     "query": "label_values(azure_devops_project_info, projectName)"
    }
   },
   { "name": "AzureDevOpsOrg", "query": "example" }
  ]
 },
 "panels": [
  { "title": "Pipeline agents", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Agent pools",
   "type": "stat",
   "gridPos": { "h": 9, "w": 13, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(\nmax by (agentPoolID, agentPoolName) (\n  azure_devops_agentpool_info\n  * on (agentPoolID) group_left() (\n    count by(agentPoolID) (\n      azure_devops_agentpool_agent_info\n{enabled=\"true\",status=\"online\"}\n    )\n  )\n)\n)",
     "legendFormat": "{{agentPoolName}}"
    }
   ]
  },
  {
   "title": "Agent pools",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sort_desc(\nmax by (agentPoolID, agentPoolName) (\n  azure_devops_agentpool_info\n  * on (agentPoolID) group_left() (\n    count by(agentPoolID) (\n      azure_devops_agentpool_agent_info\n{enabled=\"true\",status=\"online\"}\n    )\n  )\n)\n)",
     "legendFormat": "{{agentPoolName}}"
    }
   ]
  },
  { "title": "Job queue", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Queued jobs",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "azure_devops_agentpool_queue_length\n* on (agentPoolID) group_left(agentPoolName) (azure_devops_agentpool_info)",
     "legendFormat": "{{agentPoolName}}"
    }
   ]
  },
  {
   "title": "Running jobs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count (azure_devops_agentpool_agent_job)"
    }
   ]
  },
  {
   "title": "Jobs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(max_over_time(azure_devops_agentpool_agent_job[8h]))"
    }
   ]
  },
  {
   "title": "Jobs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(max_over_time(azure_devops_agentpool_agent_job[1w]))"
    }
   ]
  },
  {
   "title": "Jobs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(max_over_time(azure_devops_agentpool_agent_job[4w]))"
    }
   ]
  },
  {
   "title": "Wait time (by pool)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by(agentPoolID) (\n  rate(azure_devops_stats_agentpool_builds_wait_sum[1h])\n  / rate(azure_devops_stats_agentpool_builds_wait_count[1h])\n)\n* on(agentPoolID) group_left(agentPoolName) (max by (agentPoolID,agentPoolName) (azure_devops_agentpool_info{isHosted=\"false\"}))",
     "legendFormat": "{{agentPoolName}}"
    }
   ]
  },
  {
   "title": "Max build time (by pool)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max by(agentPoolID) (\n  rate(azure_devops_stats_agentpool_builds_duration_sum[1h])\n  / rate(azure_devops_stats_agentpool_builds_duration_count[1h])\n)\n* on(agentPoolID) group_left(agentPoolName) (max by (agentPoolID,agentPoolName) (azure_devops_agentpool_info{isHosted=\"false\"}))",
     "legendFormat": "{{agentPoolName}}"
    }
   ]
  },
  {
   "title": "Max build time (by project)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "\nmax by(projectID) (\n  rate(azure_devops_stats_project_builds_duration_sum[1h])\n  / rate(azure_devops_stats_project_builds_duration_count[1h])\n)\n* on(agentPoolID) group_left(agentPoolName) (max by (agentPoolID,agentPoolName) (azure_devops_agentpool_info))",
     "legendFormat": "{{projectName}}"
    }
   ]
  },
  {
   "title": "Queue length",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max by (agentPoolName) (\n  azure_devops_agentpool_queue_length\n  * on(agentPoolID) group_left(agentPoolName) (max by (agentPoolID,agentPoolName) (azure_devops_agentpool_info))\n)",
     "legendFormat": "{{agentPoolName}}"
    }
   ]
  },
  {
   "title": "Agent pool utilization",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max by (agentPoolName, agentPoolID) (\n  azure_devops_agentpool_usage\n  * on(agentPoolID) group_left(agentPoolName) (max by (agentPoolID,agentPoolName) (azure_devops_agentpool_info))\n)",
     "legendFormat": "{{ agentPoolName }}"
    }
   ]
  },
  {
   "title": "Running jobs",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "label_replace(\r\n  ( \r\n    azure_devops_agentpool_agent_job{definitionName!=\"PoolMaintenance\"}\r\n    * on (agentPoolAgentID) group_left(agentPoolID,agentPoolAgentName) azure_devops_agentpool_agent_info\r\n    * on (agentPoolID) group_left(agentPoolName) (azure_devops_agentpool_info)\r\n  )\r\n  , \"projectID\", \"$1\", \"scopeID\", \"^(.+)$\"\r\n)\r\n* on (projectID) group_left(projectName) (azure_devops_project_info)\r\n\r\n* 1000"
    }
   ]
  },
  {
   "title": "Running agent jobs",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (agentPoolName, agentPoolID) (\r\n  azure_devops_agentpool_info\r\n  * on (agentPoolID) group_left() (\r\n    sum by(agentPoolID) (\r\n      azure_devops_agentpool_agent_info\r\n      * on (agentPoolAgentID) group_left() (\r\n        count by (agentPoolAgentID) (azure_devops_agentpool_agent_job{definitionName!=\"PoolMaintenance\"})\r\n      )\r\n    )\r\n  )\r\n)",
     "legendFormat": "{{ agentPoolName }}"
    }
   ]
  },
  {
   "title": "Job history",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "label_replace(\r\n  ( \r\n    max_over_time(azure_devops_agentpool_agent_job{definitionName!=\"PoolMaintenance\"}[6h])\r\n    * on (agentPoolAgentID) group_left(agentPoolID,agentPoolAgentName) azure_devops_agentpool_agent_info\r\n    * on (agentPoolID) group_left(agentPoolName) (azure_devops_agentpool_info)\r\n  )\r\n  , \"projectID\", \"$1\", \"scopeID\", \"^(.+)$\"\r\n)\r\n* on (projectID) group_left(projectName) (azure_devops_project_info)\r\n\r\n* 1000"
    }
   ]
  },
  { "title": "Project info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "SourceCode",
   "type": "stat",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "commits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum( \n  increase(azure_devops_repository_commits[31d])\n  * on (projectID) group_left(projectName) (azure_devops_project_info{projectName=\"$Project\"})\n)",
     "legendFormat": "last 31 days"
    },
    {
     "expr": "sum( \n  increase(azure_devops_repository_commits[31d])\n  * on (projectID) group_left(projectName) (azure_devops_project_info{projectName=\"$Project\"})\n) / 31",
     "legendFormat": "per day"
    }
   ]
  },
  {
   "title": "Pipeline jobs",
   "type": "stat",
   "gridPos": { "h": 7, "w": 9, "x": 9, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "runs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  sum by(projectID, buildDefinitionID) (\n    increase(azure_devops_stats_project_builds_duration_count[31d])\n  )\n  * on(projectID) group_left(projectName) (azure_devops_project_info{projectName=\"$Project\"})\n)",
     "legendFormat": "last 31 days"
    },
    {
     "expr": "sum(\n  sum by(projectID, buildDefinitionID) (\n    increase(azure_devops_stats_project_builds_duration_count[31d])\n  )\n  * on(projectID) group_left(projectName) (azure_devops_project_info{projectName=\"$Project\"})\n) / 31",
     "legendFormat": "per day"
    }
   ]
  },
  {
   "title": "Pipeline success rate",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  sum by(projectID, buildDefinitionID) (\n    increase(azure_devops_stats_project_builds_duration_count{result=\"succeeded\"}[31d])\n  )\n  * on(projectID) group_left(projectName) (azure_devops_project_info{projectName=\"$Project\"})\n)\n/\nsum(\n  sum by(projectID, buildDefinitionID) (\n    increase(azure_devops_stats_project_builds_duration_count[31d])\n  )\n  * on(projectID) group_left(projectName) (azure_devops_project_info{projectName=\"$Project\"})\n)",
     "legendFormat": "pipeline success"
    }
   ]
  },
  {
   "title": "Open Pull requests",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "time() - \r\n(\r\n  ( \r\n    azure_devops_pullrequest_info{isDraft=\"false\"}\r\n    * on (projectID) group_left(projectName) azure_devops_project_info{projectName=\"$Project\"}\r\n  )\r\n  * on (repositoryID) group_left(repositoryName) azure_devops_repository_info\r\n  * on (pullrequestID) group_left(job) azure_devops_pullrequest_status{type=\"created\"}\r\n)"
    }
   ]
  },
  {
   "title": "Max build duration time",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "label_join(\n  max by(projectID, buildDefinitionID) (\n    azure_devops_stats_project_builds_duration_sum\n    / azure_devops_stats_project_builds_duration_count\n  )\n  * on(projectID) group_left(projectName) (azure_devops_project_info{projectName=\"$Project\"})\n  * on(buildDefinitionID) group_left(buildDefinitionName, path) (azure_devops_build_definition_info)\n  , \"buildDefinitionFullname\", \"\\\\\",  \"path\", \"buildDefinitionName\"\n)",
     "legendFormat": "{{buildDefinitionFullname}}"
    }
   ]
  },
  {
   "title": "Max wait duration time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "topk(\r\n  5,\r\n  max by(projectID, buildDefinitionID) (\r\n    azure_devops_stats_project_builds_wait_sum\r\n    / azure_devops_stats_project_builds_wait_count\r\n  )\r\n  * on(projectID) group_left(projectName) (azure_devops_project_info{projectName=\"$Project\"})\r\n  * on(buildDefinitionID) group_left(buildDefinitionName) (azure_devops_build_definition_info)\r\n)",
     "legendFormat": "{{buildDefinitionName}}"
    }
   ]
  },
  {
   "title": "Max build duration time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "topk(\n  5,\n  max by(projectID, buildDefinitionID) (\n    azure_devops_stats_project_builds_duration_sum\n    / azure_devops_stats_project_builds_duration_count\n  )\n  * on(projectID) group_left(projectName) (azure_devops_project_info{projectName=\"$Project\"})\n  * on(buildDefinitionID) group_left(buildDefinitionName) (azure_devops_build_definition_info)\n)",
     "legendFormat": "{{buildDefinitionName}}"
    }
   ]
  },
  {
   "title": "Repo size",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "topk(\n  5,\n  azure_devops_repository_stats{type=\"size\"}\n  * on(projectID) group_left(projectName) (azure_devops_project_info{projectName=\"$Project\"})\n  * on(repositoryID) group_left(repositoryName) (azure_devops_repository_info)\n)",
     "legendFormat": "{{repositoryName}}"
    }
   ]
  },
  {
   "title": "Commits",
   "type": "petrslavotinek-carpetplot-panel",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 68 },
   "targets": [
    {
     "expr": "sum( \n  increase(azure_devops_repository_commits[1h])\n  * on (projectID) group_left(projectName) (azure_devops_project_info{projectName=\"$Project\"})\n)"
    }
   ]
  }
 ]
}